export const SET_PAGES = "SET_PAGES";
export const SET_SIDEBAR_LINKS = "SET_SIDEBAR_LINKS";
export const SET_HEADER_LINKS = "SET_HEADER_LINKS";
export const SET_JUMBOTRON_CONTENT = "SET_JUMBOTRON_CONTENT";
export const IS_LOADED = "IS_LOADED";
export const SHOW_JUMBOTRON_MODAL = "SHOW_JUMBOTRON_MODAL";
export const HIDE_JUMBOTRON_MODAL = "HIDE_JUMBOTRON_MODAL";
export const TOGGLE_JUMBOTRON_MODAL = "TOGGLE_JUMBOTRON_MODAL";

export const SHOW_MOBILE_MODAL = "SHOW_MOBILE_MODAL";
export const HIDE_MOBILE_MODAL = "HIDE_MOBILE_MODAL";
export const TOGGLE_MOBILE_MODAL = "TOGGLE_MOBILE_MODAL";
